### PR TITLE
Beginning Stages of adding a cart

### PR DESCRIPTION
**Pull request by JakeInman**

### CODE REVIEW

**Comment by JakeInman** [comment]
I am having a little bit of trouble. I feel like I may be kind of on the right path, or maybe i'm over thinking some of this. I may just need a gentle shove in the right direction.

**Comment by evanlurvey** [comment]
You still need to review the files you added. There are some PYC files and a ds store. We need to remove those. 

As far as the cart goes how does this work for more than one shopper?

**Comment by JakeInman** [comment]
Damnit. I don't understand the deal with this .gitignore file. Why does it never seem to hide anything for me?
I'm thinking that this doesn't work for more than one person because i made the cart an array. If I make it a dict, like my items, then I should be able to add a cart for each user. I will give that a shot and post some code in here before I push it up.

**Comment by evanlurvey** [comment]
It’s probably because the files are already cached or something goofy. Try just removing them with git rm. 

The dict could work, what are you going to use for a key and then what will be the value of the dict?

**Comment by JakeInman** [comment]
Ok, I pushed up some changes. All of the current features work as far as I could tell! Let me know any questions/comments/concerns.
I would like it if my cart costs and item count automatically updated when I added another item, but idk if you want to go that deep or focus elsewhere.

**Pull request merged**
